version: '3,7'
services:
  mysqldb:
    restart: always
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./scheme:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=test
      - MYSQL_USER=michael
      - MYSQL_PASSWORD=SCOTTdm13177